language: python
python:
  - "2.7"
sudo: required
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y zip sudo wget bzip2 tar -y --force-yes
  - sudo apt-get clean
  - wget -O bootstrap.py https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py && sudo python bootstrap.py
install:
  - wget "http://ftp.mozilla.org/pub/thunderbird/releases/`cat release`/source/thunderbird-`cat release`.source.tar.bz2"
  - tar xjvf "thunderbird-`cat release`.source.tar.bz2"
  - cd comm-*
  - python client.py checkout
before_script:
  - echo 'ac_add_options --enable-application=mail' >> .mozconfig
  - echo 'ac_add_options --enable-application=calendar' >> .mozconfig
  - echo 'ac_add_options --enable-optimize' >> .mozconfig
  - echo 'CONCURRENCY=$(( `grep processor /proc/cpuinfo | wc -l` + 2 ))' >> .mozconfig
  - echo 'mk_add_options MOZ_MAKE_FLAGS="-j$CONCURRENCY"' >> .mozconfig
  - echo 'ac_add_options --with-ccache=/usr/bin/ccache' >> .mozconfig
script: ./mozilla/mach build
after_script: ls
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - ".mozconfig"
  skip_cleanup: true
  on:
    tags: true