language: python
python:
- '2.7'
sudo: required
before_install:
- sudo apt-get update -y
- sudo apt-get install -y zip sudo wget bzip2 tar -y --force-yes
- sudo apt-get clean
- echo "alias add-apt-repository='add-apt-repository -y'" >> ~/.bashrc
- echo "alias add-apt-repository='add-apt-repository -y'"  | sudo tee --append /root/.bashrc
- echo "alias sudo='sudo '"  | sudo tee --append /root/.bashrc
- alias add-apt-repository='add-apt-repository -y'
- alias sudo='sudo '
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 323293EE
- sudo add-apt-repository -y ppa:mercurial-ppa/releases
- wget -O bootstrap.py https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py
  && sudo python bootstrap.py --application-choice desktop --no-interactive
install:
- wget "http://ftp.mozilla.org/pub/thunderbird/releases/`cat release`/source/thunderbird-`cat
  release`.source.tar.bz2"
- tar xjvf "thunderbird-`cat release`.source.tar.bz2"
- cd comm-*
- python client.py checkout
before_script:
- echo 'ac_add_options --enable-application=mail' >> .mozconfig
- echo 'ac_add_options --enable-application=calendar' >> .mozconfig
- echo 'ac_add_options --enable-optimize' >> .mozconfig
- echo 'CONCURRENCY=$(( `grep processor /proc/cpuinfo | wc -l` + 2 ))' >> .mozconfig
- echo 'mk_add_options MOZ_MAKE_FLAGS="-j$CONCURRENCY"' >> .mozconfig
- echo 'ac_add_options --with-ccache=/usr/bin/ccache' >> .mozconfig
script: "./mozilla/mach build"
after_script: ls
deploy:
  provider: releases
  api_key:
    secure: JkkcrQqsZI5XZfFKaIFoiY7CM6/FFCVCGnGrDV68jnzolzwXGBbRpi3CDxR8pKZewQIFAKwF0Q5tnwhzoTsopquydUGVF+uATGiv81y7DbtLy2VOSzAn+zwIDC5IICO1+jr3ofYt14JM+9nT/+ubTAF3nSkIGmGSTIzlL3CpcebVEgVhN8cSxSOrfrvWKfRs5OPffHiWyRUDWmz0Uq8GyFJqaitDv5V5HJfyURvA02oGknEfBiY48n/icCoSNt6X+4EyxclgLfltFz1qg6Rxw8hJWodbSmGOpIb9QlfVLaiDg/75akgGM0StF0Xv4787ooZ3Rn/YZ5Dh8IEzzERJ30Aox+sk0fP58HmrU1Hrk1hvjuzIz44qr3B2HXfhe+G5ACZaAiGQIc7U+oXLOtxoxNuQYyoYYT5/P8R7UQ13YQ2gw2NXRvMPA7Vc6YecsrMdf0b5et4D+SYhcNCWrsr4VWZuUEtu9CKw0BBvdlhNtbQZgixRV8P6zHjReeG4rvrFID9Ofdy/u6b5B0qDZQZHFCo7/L85YJTfXrfFzSRPRLloKeW5iKvpXn7Gegfdrr61xFMhG6O3EtOkc/rGct+6nEihrQDDKd43yzu5v5NwwphECE75oYciHryudrN+joPqxqkmInTLMqt4gUvY4N1mz88IJjvTjyIvN6fmMXazYfM=
  file: ".mozconfig"
  on:
    repo: DaAwesomeP/thunderbird-64
